# -*- coding: utf-8 -*-
"""Setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sTrB7Wdnk8-2SHVBsj6GkkSnmSWRkm-y
"""

from setuptools import setup

setup(name='gym_foo',
      version='0.0.1',
      install_requires=['gym']#And any other dependencies required
)